/**
 * Vector animation assets — Lottie and Rive.
 *
 * ── What the evaluation actually found ──────────────────────────────────
 *
 * Both runtimes are MIT and free for commercial use with no attribution.
 * The interesting difference is the ASSET PIPELINE, not the code:
 *
 * LOTTIE (lottie-web, MIT, ~250 KB)
 *   Plays JSON authored in After Effects/Bodymovin or generated by code.
 *   Because JSON is just JSON, `public/assets/agent-core.json` is generated
 *   programmatically for this site — a 2s loopable "agent core". No licensing
 *   question, no designer required, but hand-authoring is only practical for
 *   simple vector work.
 *
 * RIVE (@rive-app/canvas, MIT, smaller player)
 *   Better runtime for interactive, state-machine-driven vector work, and the
 *   player is a fraction of Lottie's size. The catch: `.riv` is a compiled
 *   binary that can ONLY be produced by the Rive editor, and exporting one
 *   requires a paid plan (Cadet, ~$9/seat/mo). You can *play* any `.riv` for
 *   free, which is why this site demonstrates Rive with the MIT-licensed
 *   `rating.riv` from rive-app/rive-react on the lab page only — a star-rating
 *   widget has no place in an AI-engineering portfolio.
 *
 * Both libraries are dynamically imported, so neither is in the critical path.
 */
import { one, prefersReducedMotion } from '../lib/prefs.js';

/** Default `.riv`, used when a slot does not specify its own `data-rive-slot`. */
const DEFAULT_RIVE_SRC = null;

/** Optional state machine name to auto-play inside the `.riv`. */
const RIVE_STATE_MACHINE = null;

/* ── Lottie ──────────────────────────────────────────────────── */

async function initLottie() {
  const slots = Array.from(document.querySelectorAll('[data-lottie-slot]'));
  if (!slots.length) return [];

  // `lottie_light` drops the expression engine — which this site never uses and
  // which is the only reason the full player needs `eval`. Roughly halves the
  // chunk and removes a real security smell.
  const { default: lottie } = await import('lottie-web/build/player/lottie_light');
  const animations = [];

  for (const slot of slots) {
    const src = slot.dataset.lottieSlot || '/assets/agent-core.json';

    const animation = lottie.loadAnimation({
      container: slot,
      renderer: 'svg',
      loop: true,
      autoplay: !prefersReducedMotion,
      path: src,
      rendererSettings: {
        preserveAspectRatio: 'xMidYMid meet',
        progressiveLoad: true,
      },
    });

    // Reduced motion: park on a representative frame instead of animating.
    if (prefersReducedMotion) animation.goToAndStop(60, true);

    const ok = await new Promise((resolve) => {
      animation.addEventListener('DOMLoaded', () => resolve(true));
      animation.addEventListener('data_failed', () => resolve(false));
    });

    // Expose the player so the lab page can drive it (play/pause/scrub).
    slot.__lottie = animation;
    slot.dataset.lottieReady = String(ok);
    if (ok) slot.hidden = false;

    animations.push(animation);
  }

  return animations;
}

/* ── Rive ────────────────────────────────────────────────────── */

async function initRive() {
  const slots = Array.from(document.querySelectorAll('[data-rive-slot]'));
  if (!slots.length) return [];

  const { Rive, Layout, Fit, Alignment } = await import('@rive-app/canvas');
  const instances = [];

  for (const slot of slots) {
    const src = slot.dataset.riveSlot || DEFAULT_RIVE_SRC;
    const label = slot.dataset.riveName || 'rive';

    if (!src) {
      slot.dataset.riveError = 'no asset configured';
      continue;
    }

    const canvas = document.createElement('canvas');
    canvas.setAttribute('aria-label', `${label} animation`);
    canvas.setAttribute('role', 'img');
    slot.appendChild(canvas);

    // Rive loads asynchronously and reports through callbacks. Resolve only
    // once the asset is actually ready, so callers can report the true state
    // instead of racing the loader.
    const ready = new Promise((resolve) => {
      const instance = new Rive({
        src,
        canvas,
        autoplay: !prefersReducedMotion,
        stateMachines: slot.dataset.riveStateMachine || RIVE_STATE_MACHINE || undefined,
        layout: new Layout({ fit: Fit.Contain, alignment: Alignment.Center }),
        onLoad: () => {
          instance.resizeDrawingSurfaceToCanvas();
          slot.hidden = false;
          slot.dataset.riveReady = 'true';
          resolve(instance);
        },
        onLoadError: (error) => {
          slot.dataset.riveError = String(error?.message || 'load failed');
          resolve(null);
        },
      });
      slot.__rive = instance;
    });

    const instance = await ready;
    if (instance) instances.push(instance);
  }

  return instances;
}

/* ── Public API ──────────────────────────────────────────────── */

export async function initVectorAssets() {
  const results = await Promise.allSettled([initLottie(), initRive()]);

  results.forEach((result, index) => {
    if (result.status === 'rejected') {
      const which = index === 0 ? 'lottie' : 'rive';
      console.warn(`[site] ${which} layer skipped:`, result.reason);
    }
  });

  return {
    lottie: results[0].status === 'fulfilled' ? results[0].value : [],
    rive: results[1].status === 'fulfilled' ? results[1].value : [],
  };
}
